### ISSUE TITLE
Copiar link interno não funciona

### ISSUE THREAD

**Issue by pedrosino** [jonatasrs/sei#103]
No console aparecem as mensagens de execução, mas o ícone dos links não está aparecendo mais.

**Comment by neijobson** [comment]
O problema da não exibição do botão "L" sobre os Processos para copiar Link Interno do Processo apareceu a partir da versão do SEI 3.0.15.

Além da correção do Bug, poderiam avaliar apresentar o mesmo botão "L" para copiar Link Interno para Documento, pois é diferente do botão "C".

Veja no link a seguir o padrão de Link Interno para Processo e sobre Documento: https://docs.google.com/document/d/1SvHb_qLYXTS2ZLkjdhJqm_PTUGFbGgMItuuuLLf3BJA/pub#h.bu8sxno60vwr

**Comment by jonatasrs** [comment]
Corrigido na versão atual 4.3.1
