### ISSUE TITLE
Incluir documentos externos ao arrastar arquivos nao esta funcionando

### ISSUE THREAD

**Issue by viniciusseuqram** [jonatasrs/sei#104]
quando tento arrastar documentos externos,para icluir no processo 
nao esta funcionando

**Comment by luiscrjunior** [comment]
Boa noite. Por aqui, tudo funcionando. Pode dar mais alguma informação? Sugiro verificar se o processo está aberto no seu ambiente, se não o upload não funciona. Ainda, quando o nome do arquivo é muito grande, ele dá erro.

**Comment by luiscrjunior** [comment]
Como não há outros relatos de problemas com essa funcionalidade, estou fechando a issue.
