### ISSUE TITLE
Preferências não ficam salvas

### ISSUE THREAD

**Issue by pedrosino** [jonatasrs/sei#111]
Já há algum tempo não consigo salvar as preferências da extensão.
Num primeiro momento parece que funcionou, mas ao abrir um processo e voltar a tela principal, as opções voltam para o padrão.

Já restaurei o Firefox, criei um novo perfil, e não consigo resolver.

**Comment by EricOliveira1980** [comment]
Você sincroniza as extensões do Firefox entre os seus dispositivos, um com SEI++ e outro sem, ou ainda ,cada um com preferências do SEI++ diferentes? Já me aconteceu isso, e só parou o problema quando não permiti mais a sincronização de extensões.

**Comment by pedrosino** [comment]
Não sincronizo...nem tenho conta no Firefox.

**Comment by luzemario** [comment]
Uso a sincronização do Firefox em todos os meus dispositivos. No Linux/Android nunca tive esse problema, mas no Windows 10 ele é recorrente. Não importa se a sincronização está ativada ou desativada, no Windows, ele simplesmente salva o cookie quando quer. Aparenta ser algum tipo de proteção oculta no SO.

**Comment by jonatasrs** [comment]
Não consegui reproduzir o erro nos navegadores Chrome e Firefox nas versões atuais, assim vou encerrar essa issue.
