### ISSUE TITLE
Feature request - Criar novo documento usando o atual como modelo

### ISSUE THREAD

**Issue by weltonrodrigo** [jonatasrs/sei#118]
Acho que é um caso de uso comum "duplicar" um documento no SEI no mesmo processo.

Eu, como usuário do SEI, gostaria de poder, ao trabalhar num processo, incluir rapidamente um documento usando como modelo outro do mesmo processo. A funcionalidade poderia estar acessível como um ícone na árvore ao lado do nome do documento ou como um botão na lista de ações de um documento. Ao clicar na funcionalidade, um novo documento do mesmo tipo do original é criado na árvore e seu conteúdo é o mesmo do original. Caso isso não seja possível, ao clicar no ícone, sou levado diretamente à tela "Gerar Documento", já com o número "documento modelo" preenchido.

**Comment by luiscrjunior** [comment]
#129
