### ISSUE TITLE
Botão para copiar o número do processo e seu link sumiram

### ISSUE THREAD

**Issue by kokbira** [jonatasrs/sei#120]
Não sei se posso reportar bem como um bug, mas não encontrei nenhuma referência (quando procurei há alguns meses) à remoção das funcionalidades de botão para copiar número do processo e botão para copiar o link do processo, que sumiram com as atualizações do SEI++.

Na concepção de uma funcionalidade que sumiu com uma atualização sem referência documental à sua retirada, inclusive com a descrição na loja do Chrome persistindo com a inclusão da funcionalidade ("* Funcionalidade para copiar o número do processo e do documento"), informo o que considero um bug, ou para adicionar a funcionalidade novamente ou para corrigir a documentação e referências à funcionalidade.

**Comment by kokbira** [comment]
Parece que com a atualização de 21/09/20 a funcionalidade de copiar o link dos documentos e o nº do processo voltou. Muito obrigado :)

**Comment by luiscrjunior** [comment]
Olá! o botão de copiar o link do processo aparece para mim. Para mais alguém não?

O botão de copiar o número do processo em princípio sumiu depois das atualizações do SEI, mas podemos copiar o número do processo clicando no ícone ao lado esquerdo do processo (função nativa do SEI). Talvez devemos retirar essa funcionalidade do SEI++ e atualizar a documentação? @jonatasrs @hebertmm

**Comment by dalcib** [comment]
A função nativa do SEI de copiar o número do processo está funcionando, tanto no Chrome quanto no Firefox.
Seria bom incluir da documentação, porque poucos tem conhecimento desta ferramenta.
