### ISSUE TITLE
Problema na exibição de documentos

### ISSUE THREAD

**Issue by PriGonsalves** [jonatasrs/sei#19]
A proposta da extensão é boa. Ainda não utilizei todos os recursos, mas já pude observar que a visualização de documentos está bem limitada, cortando parte do documento. Pra visualizar uma página inteira de um documento (em .pdf ou um documento interno) ou damos zoom ou abrimos numa nova guia. 
![sei](https://user-images.githubusercontent.com/33154803/32105300-bc369432-bb06-11e7-973f-c57f36a059cc.png)
![sei zoom](https://user-images.githubusercontent.com/33154803/32105336-dc4f92be-bb06-11e7-91db-cb0a9e266c66.png)

**Comment by jonatasrs** [comment]
Olá tudo bem,

Obrigado pelo feedback. Poderia informar se este problema ocorreu após a instalação do complemento?
Informar também a versão os SEI que você utiliza.
Se quiser pode me mandar por e-mail: jonatas.eletrica@gmail.com

Abraços
Jonatas

**Comment by jonatasrs** [comment]
Bug na facilidade "menu suspenso", foi corrido para a próxima versão 3.0
