### ISSUE TITLE
Alteração na máscara do domínio

### ISSUE THREAD

**Issue by marcelopbarros** [jonatasrs/sei#22]
Queria propor uma alteração nas máscaras do link onde o script é executado. Alterar, a exemplo de * *://*/sei/* para *://*.gov.br/sei/*. A justificativa é que percebi que o script é executado em páginas como https://github.com/jonatasrs/sei/. Acredito que não há impacto já que todos os órgãos que utilizarão o plugin estão em domínio .gov.br.

**Comment by jonatasrs** [comment]
Temos alguns órgãos, como as universidades que não utilizam o "gov.br", mas talvez podemos mudar para:  "*://*.br/sei/*", já restringiria um pouco mais.

**Comment by jonatasrs** [comment]
Incluído na commit **e57b8ecc75bb64332f295d6a559ebc36987a0b91**
