### ISSUE TITLE
Retirar termo Uso apenas na Anatel do Clique Menos

### ISSUE THREAD

**Issue by marcelopbarros** [jonatasrs/sei#23]
Seria possível excluir o termo **para uso somente na Anatel** do complemento **Clique menos**? Acredito que seja uma demanda que se encaixe bem no perfil dos demais órgãos. Mostrei para o pessoal aqui e me parece ter havido uma boa aceitação, até por ser bastante personalizável.

**Comment by jonatasrs** [comment]
Seria sim, mas temos que garantir que funcione nos outros órgãos. Como não sabemos se funciona, colocamos o termo somente para a Anatel.
Temos que verificar se os itens selecionáveis são um padrão nos demais órgãos, ou ver se tem como obter essa listagem dinamicamente na tela de opções.

**Comment by marcelopbarros** [comment]
Bom, como eu comentei, a aceitação desse script foi muito boa entre os colegas da minha sala. Acredito que muitos vão gostar. Mas alguns poucos acabam testando _de curiosos_. Acho que esse termo **para uso somente na Anatel** pode afastar o pessoal de testar e se beneficiar. Se der erro em algum órgão depois, a gente corrige, rs. Tamo aí pra isso! ;-)

**Comment by jonatasrs** [comment]
Incluído na commit **a3ffc3be7b0794bceaa03c84ebbec5b9d1fef6c5**
