### ISSUE TITLE
Atualizar o script RetirarSobrestamentoReabrirEmBloco

### ISSUE THREAD

**Issue by jonatasrs** [jonatasrs/sei#30]
Melhorar a apresentação do retorno do script RetirarSobrestamentoReabrirEmBloco, como por exemplo, exibir mensagem "Executado com sucesso" ou "Houve erros no processamento, exibir log".

**Comment by marcelopbarros** [comment]
Concordo com ambas as modificações, melhorariam mesmo. Seria interessante quebrar essas issue em duas distintas, pois tratam de assuntos não relacionados.

**Comment by jonatasrs** [comment]
Ok, dividi na issue #32
