### ISSUE TITLE
[NOVO SCRIPT] Abrir documento diretamente em nova Aba/Janela

### ISSUE THREAD

**Issue by jonatasrs** [jonatasrs/sei#36]
Desenvolver novo script para possibilitar abrir um documento diretamente em nova aba sem carrega-lo no iframe.

**Comment by marcelopbarros** [comment]
Já temos esse script. Só não coloquei ele na versão 3.0 devido a falta de tempo. No caso, o que usamos adiciona um botão (Abrir em Nova Aba) naquela barra de ferramentas, e permite abrir o documento em uma nova aba. Muito prático pra verificar documentos.

**Comment by jonatasrs** [comment]
Isso também é interessante, mas nesse caso seria de possibilitar abrir os documentos diretamente do link da arvore do processo. Isto evitaria ter que abrir um pdf no iframe e somente depois conseguir abrir em nova aba, o que causa dois carregamentos para o mesmo documento.

**Comment by jonatasrs** [comment]
Commit **ea92d64258e70d7324fd1b262cf7413af7515f7d**
