### ISSUE TITLE
Permitir anexar mais de um arquivo por vez desde que possuam as mesmas características (isto é, mesmo preenchimento de campos).

### ISSUE THREAD

**Issue by fernandaramos84** [jonatasrs/sei#63]
Permitir anexar mais de um arquivo por vez desde que possuam as mesmas características (isto é, mesmo preenchimento de campos)

**Comment by jonatasrs** [comment]
Olá Fernanda, esse tipo de funcionalidade teria que ser implementada no próprio núcleo do SEI.
