### ISSUE TITLE
Ao colocar o mouse sobre o número do processo, também mostrar a anotação no tooltip - caso exista.

### ISSUE THREAD

**Issue by fernandaramos84** [jonatasrs/sei#65]
Ao colocar o mouse sobre o número do processo, também mostrar a anotação no tooltip - caso exista.

**Comment by jonatasrs** [comment]
@fernandaramos84 ao passar o mouse sobre o processo, já é mostrado um tooltip com a especificação do processo, a anotação é mostrada ao passar o mouse sobre o ícone da anotação. Nesse caso, qual seria a vantagem dessa funcionalidade?
