### ISSUE TITLE
[Funcionalidade Menu Suspenso] Menu não aparece no SIP

### ISSUE THREAD

**Issue by LThiesen** [jonatasrs/sei#76]
Com a funcionalidade do menu suspenso ativada não é possivel exibir as opções para administração de usuarios.
![image](https://user-images.githubusercontent.com/43725694/46258999-12e03200-c4a9-11e8-8847-26c8c5eb4429.png)
![image](https://user-images.githubusercontent.com/43725694/46259031-8124f480-c4a9-11e8-9c38-611dac568df3.png)

**Comment by jonatasrs** [comment]
Será tratado na issue #78
