### ISSUE TITLE
Variável para assinatura

### ISSUE THREAD

**Issue by wbcampos** [jonatasrs/sei#85]
Olá, 
Existe no SEI uma variável que preenche o nome da pessoa que está criando o documento?
(para ser utilizada na assinatura. a pessoa cria o documento e automaticamente aparece o nome dela no fim do texto).

**Comment by jonatasrs** [comment]
Olá, a pessoa que criou o documento não deveria aparecer no conteúdo do documento. Fica apenas no histórico do documento. Não existe uma variável deste tipo no sei.
Abraços.
